---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    app: tekton-catalog
  name: tekton-catalog-pipeline
spec:
  description: A sample pipeline that interacts with GitHub <br /><br /> **WorkFlow** <br /> ![workflow](https://storage.googleapis.com/abaker9-temp/pipeline-workflow1.png) <br /><br /> **Pipeline** <br /> ![pipeline](https://storage.googleapis.com/abaker9-temp/hello-github.png)
  finally:
  - name: notify-any-failure
    when:
      - input: $(tasks.status)
        operator: in
        values: ["Failed"]
    params:
      - name: webhook-secret
        value: slack
      - name: message
        value: "git clone is failed"
      - name: icon-emoji
        value: ':Failed:'
    taskRef:
      kind: Task
      name: send-to-slack-channel
  params:
  - description: url to clone with https
    name: repo_url
    default: "https://github.com/manojbison/pipeline-status.git"
  tasks:
  - name: clone
    params:
    - name: url
      value: $(params.repo_url)
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: source
  workspaces:
  - description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for verifying, building, and pushing files
    name: source
